# Generated by Django 3.1.1 on 2020-10-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201022_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Admin', 'admin'), ('Analyst', 'analyst')], max_length=50),
        ),
    ]
