# Generated by Django 3.1.1 on 2020-09-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
