# Generated by Django 3.1.1 on 2020-10-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
